<script setup>
import { computed, ref } from "vue";

const props = defineProps({
  lang: {
    type: String,
    default: "en",
  },
});

const loading = ref(false);
const output = ref("");
const error = ref("");
const copied = ref(false);

const messages = {
  en: {
    label: "Extract coordinates from a .sum file (from full_output.zip generated by SCRS-PPP SPARK)",
    fileAriaLabel: "Select a .sum text file",
    copy: "Copy",
    copied: "Copied",
    noFile: "Please select a file.",
    readError: "Unable to read the selected file.",
    parseError: "Could not find coordinates in the file.",
    unknownError: "Unknown error",
    outputLabel: "Formatted output",
  },
  fr: {
    label: "Extraire les coordonnées depuis un fichier .sum (dans full_output.zip généré par SCRS-PPP SPARK)",
    fileAriaLabel: "Sélectionnez un fichier texte .sum",
    copy: "Copier",
    copied: "Copié",
    noFile: "Veuillez sélectionner un fichier.",
    readError: "Impossible de lire le fichier sélectionné.",
    parseError: "Impossible de trouver des coordonnées dans le fichier.",
    unknownError: "Erreur inconnue",
    outputLabel: "Sortie formatée",
  },
};

const t = computed(() => messages[props.lang] ?? messages.en);

function normalizeText(text) {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .replace(/[‐-‒–—]/g, "-");
}

function readFileAsText(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = () => resolve(String(reader.result ?? ""));
    reader.onerror = () => reject(new Error("read_error"));

    reader.readAsText(file);
  });
}

function dmsToDecimal(degrees, minutes, seconds) {
  const deg = Number(degrees);
  const min = Number(minutes);
  const sec = Number(seconds);

  const sign = deg < 0 ? -1 : 1;
  const absDeg = Math.abs(deg);

  return sign * (absDeg + min / 60 + sec / 3600);
}

function parseCoordinates(text) {
  const normalized = normalizeText(text);

  const latMatch = normalized.match(
    /^POS\s+LAT\s+\S+\s+\S+\s+([+-]?\d+)\s+(\d+)\s+([0-9.]+)\s+([+-]?\d+)\s+(\d+)\s+([0-9.]+)/im,
  );

  const lonMatch = normalized.match(
    /^POS\s+LON\s+\S+\s+\S+\s+([+-]?\d+)\s+(\d+)\s+([0-9.]+)\s+([+-]?\d+)\s+(\d+)\s+([0-9.]+)/im,
  );

  const hgtMatch = normalized.match(
    /^POS\s+HGT\s+\S+\s+\S+\s+([+-]?\d+(?:\.\d+)?)\s+([+-]?\d+(?:\.\d+)?)/im,
  );

  if (!latMatch || !lonMatch || !hgtMatch) {
    return null;
  }

  const latitude = dmsToDecimal(latMatch[4], latMatch[5], latMatch[6]);
  const longitude = dmsToDecimal(lonMatch[4], lonMatch[5], lonMatch[6]);
  const height = Number(hgtMatch[2]);

  if (
    Number.isNaN(latitude) ||
    Number.isNaN(longitude) ||
    Number.isNaN(height)
  ) {
    return null;
  }

  return `${latitude.toFixed(8)} ${longitude.toFixed(8)} ${height.toFixed(3)}`;
}

async function extractFromFile(file) {
  error.value = "";
  output.value = "";
  copied.value = false;

  if (!file) {
    error.value = t.value.noFile;
    return;
  }

  loading.value = true;

  try {
    const text = await readFileAsText(file);
    const parsed = parseCoordinates(text);

    if (!parsed) {
      error.value = t.value.parseError;
      return;
    }

    output.value = parsed;
  } catch (err) {
    error.value =
      err instanceof Error && err.message === "read_error"
        ? t.value.readError
        : t.value.unknownError;
  } finally {
    loading.value = false;
  }
}

function onFileChange(event) {
  const file = event.target.files?.[0] ?? null;
  extractFromFile(file);
}

async function copyOutput() {
  if (!output.value) {
    return;
  }

  try {
    await navigator.clipboard.writeText(output.value);
    copied.value = true;
  } catch {
    const input = document.createElement("input");
    input.value = output.value;
    document.body.appendChild(input);
    input.select();
    document.execCommand("copy");
    document.body.removeChild(input);
    copied.value = true;
  }
}
</script>

<template>
  <div class="sum-extractor">
    <label class="sum-extractor__label" for="sum-file-input">
      {{ t.label }}
    </label>

    <input
      id="sum-file-input"
      class="sum-extractor__file"
      type="file"
      accept=".sum,.txt,text/plain"
      :aria-label="t.fileAriaLabel"
      @change="onFileChange"
    >

    <label
      v-if="output"
      class="sum-extractor__label sum-extractor__label--output"
      for="sum-output"
    >
      {{ t.outputLabel }}
    </label>

    <div v-if="output" class="sum-extractor__row">
      <input
        id="sum-output"
        class="sum-extractor__input"
        type="text"
        :value="output"
        readonly
      >

      <button
        class="sum-extractor__button"
        type="button"
        @click="copyOutput"
      >
        {{ copied ? t.copied : t.copy }}
      </button>
    </div>

    <p v-if="error" class="sum-extractor__message sum-extractor__message--error">
      {{ error }}
    </p>
  </div>
</template>

<style scoped>
.sum-extractor {
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
  padding: 1rem;
  background: var(--vp-c-bg-soft);
}

.sum-extractor__label {
  display: block;
  margin-bottom: 0.75rem;
  font-weight: 600;
}

.sum-extractor__label--output {
  margin-top: 0.85rem;
}

.sum-extractor__row {
  display: flex;
  gap: 0.75rem;
  align-items: center;
}

.sum-extractor__file,
.sum-extractor__input {
  width: 100%;
  min-width: 0;
  padding: 0.7rem 0.85rem;
  border: 1px solid var(--vp-c-divider);
  border-radius: 10px;
  background: var(--vp-c-bg);
  color: var(--vp-c-text-1);
  font-family: inherit;
  box-sizing: border-box;
}

.sum-extractor__file::file-selector-button {
  margin-right: 0.75rem;
  padding: 0.7rem 1rem;
  border: 0;
  border-radius: 10px;
  background: var(--vp-c-brand-1);
  color: white;
  cursor: pointer;
  font: inherit;
  font-weight: 600;
}

.sum-extractor__file::-webkit-file-upload-button {
  margin-right: 0.75rem;
  padding: 0.7rem 1rem;
  border: 0;
  border-radius: 10px;
  background: var(--vp-c-brand-1);
  color: white;
  cursor: pointer;
  font: inherit;
  font-weight: 600;
}

.sum-extractor__input[readonly] {
  cursor: text;
}

.sum-extractor__button {
  padding: 0.7rem 1rem;
  border: 0;
  border-radius: 10px;
  background: var(--vp-c-brand-1);
  color: white;
  cursor: pointer;
  font-weight: 600;
  white-space: nowrap;
}

.sum-extractor__message {
  margin: 0.85rem 0 0;
}

.sum-extractor__message--error {
  color: #6b7280;
}

@media (max-width: 640px) {
  .sum-extractor__row {
    flex-direction: column;
    align-items: stretch;
  }
}
</style>